### ISSUE TITLE
Using new JavaScript features

### ISSUE THREAD

**Issue by austinstarin** [punkave/best-practices#56]
Opening up a discussion on ways to use new JavaScript features in the client and on the server in projects.

**Comment by boutell** [comment]
It's not a new language feature, but I'd like to see bluebird used aggressively in client projects, pretty much anywhere you would otherwise be writing a lot of `async.series`.

As for new language features, have we refined our thinking on incorporating gulp? Those two things would have to go together, at least to use it on the client. For a while it sounded like we'd decided not to gulp. I've always thought there's a place for it but we need to get consistent about what versions of gulp, settings for babel, etc. are going to be used to end "my gulp isn't right for this project itis".

**Comment by austinstarin** [comment]
I've been thinking about potentially using npm scripts for anything build related so we're not relying on gulp wrappers.

We can look further into that if you feel worth it.

**Comment by agilbert** [comment]
> I've been thinking about potentially using npm scripts for anything build related so we're not relying on gulp wrappers.

I think this is worth considering seriously. @austinstarin can you post an example in here / somewhere appropriate?

**Comment by austinstarin** [comment]
Thanks @agilbert. I'll work on this to share with the team.

**Comment by austinstarin** [comment]
Are we wed to authoring js in `always.js`?

Some questions that always come up for me...

- How do I share JavaScript between always.js files? For example, I might have methods for managing state that are useful across my front end components.

- If I was to use a build tool it seems potentially overcomplicated to manage all of these files across directories.

**Comment by austinstarin** [comment]
I'm going to close this out, we're up and running w/ babel env preset on all projects.
